Follow some Google shell scripting advice I already do pretty much everything they advise anyway Grouping functions together by using "prefix::" is quite a nice feature though. Nothing too clever, just makes use of the fact that a colon appears to be a valid character in a shell function.

diff --git a/lib/vm-datastore b/lib/vm-datastore
--- a/lib/vm-datastore
+++ b/lib/vm-datastore
@@ -27,7 +27,7 @@
 # 'vm datastore list'
 # show configured datastores
 #
-__datastore_list(){
+datastore::list(){
     local _format="%-15s %-11s %-25s %s"
     local _name _type _dataset _path _ds _spec
 
@@ -50,16 +50,16 @@ __datastore_list(){
     printf "${_format}\n" "${_name}" "${_type}" "${_path}" "${_dataset}"
 
     # load the rest
-    __config_core_get "_ds" "datastore_list"
+    config::core_get "_ds" "datastore_list"
 
     for _name in ${_ds}; do
-        __config_core_get "_spec" "path_${_name}"
+        config::core_get "_spec" "path_${_name}"
         [ -z "${_spec}" ] && continue
 
         if [ "${_spec%%:*}" = "zfs" ]; then
             _type="zfs"
             _dataset="${_spec#*:}"
-            __datastore_resolve_path "_path" "${_spec}"
+            datastore::__resolve_path "_path" "${_spec}"
         else
             _type="directory"
             _path="${_spec}"
@@ -79,41 +79,41 @@ __datastore_list(){
 # @param string _name datastore name
 # @param string _spec specification (either /path or zfs:dataset)
 #
-__datastore_add(){
+datastore::add(){
     local _name="$1"
     local _spec="$2"
     local _mount _num=0 _list _curr
 
-    [ -z "${_name}" -o -z "${_spec}" ] && __usage
-    [ "${_name}" = "default" ] && __err "additional datastore cannot be named 'default'"
-    __vm_check_name "${_name}" || __err "invalid datastore name - '${_name}'"
+    [ -z "${_name}" -o -z "${_spec}" ] && util::usage
+    [ "${_name}" = "default" ] && util::err "additional datastore cannot be named 'default'"
+    core::check_name "${_name}" || util::err "invalid datastore name - '${_name}'"
 
     # check name not in use
-    __config_core_get "_list" "datastore_list"
+    config::core_get "_list" "datastore_list"
 
     for _curr in ${_list}; do
-        [ "${_curr}" = "${_name}" ] && __err "datstore ${_name} already exists!"
+        [ "${_curr}" = "${_name}" ] && util::err "datstore ${_name} already exists!"
     done
 
     # look for zfs
     if [ "${_spec%%:*}" = "zfs" ]; then
         # try to find mountpoint
         _mount=$(mount | grep "^${_spec#*:} " |cut -d' ' -f3)
-        [ -z "${_mount}" ] && __err "${_spec} doesn't seem to be a valid, mounted dataset"
+        [ -z "${_mount}" ] && util::err "${_spec} doesn't seem to be a valid, mounted dataset"
     else
         # make sure it's a directory
-        [ ! -d "${_spec}" ] && __err "${_spec} doesn't seem to be a valid directory"
+        [ ! -d "${_spec}" ] && util::err "${_spec} doesn't seem to be a valid directory"
 
         _mount="${_spec}"
     fi
 
     # see if this is already our default datastore
-    [ "${_mount}" = "${vm_dir}" ] && __err "specified path already exists as default datastore"
+    [ "${_mount}" = "${vm_dir}" ] && util::err "specified path already exists as default datastore"
 
     # save
-    __config_core_set "datastore_list" "${_name}" "1"
-    __config_core_set "path_${_name}" "${_spec}"
-    [ $? -ne 0 ] && __err "error saving settings to configuration file"
+    config::core_set "datastore_list" "${_name}" "1"
+    config::core_set "path_${_name}" "${_spec}"
+    [ $? -ne 0 ] && util::err "error saving settings to configuration file"
 }
 
 # remove a datastore
@@ -121,16 +121,16 @@ __datastore_add(){
 #
 # @param string _name name of dataset
 #
-__datastore_remove(){
+datastore::remove(){
     local _name="$1"
 
-    [ "${_name}" = "default" ] && __err "cannot remove default datastore"
+    [ "${_name}" = "default" ] && util::err "cannot remove default datastore"
 
-    __datastore_get "${_name}" || __err "unable to locate the specified dataset"
+    datastore::get "${_name}" || util::err "unable to locate the specified dataset"
 
-    __config_core_remove "datastore_list" "${_name}"
-    __config_core_remove "path_${_name}"
-    [ $? -ne 0 ] && __err "error removing settings from configuration file"
+    config::core_remove "datastore_list" "${_name}"
+    config::core_remove "path_${_name}"
+    [ $? -ne 0 ] && util::err "error removing settings from configuration file"
 }
 
 # get the filesystem path for the specified dataset spec
@@ -140,7 +140,7 @@ __datastore_remove(){
 # @param string _spec the path spec (either directory or zfs:dataset)
 # @return non-zero on error
 #
-__datastore_resolve_path(){
+datastore::__resolve_path(){
     local _var="$1"
     local _spec="$2"
 
@@ -166,8 +166,8 @@ __datastore_resolve_path(){
 #
 # @modifies VM_DATASTORE_LIST
 #
-__datastore_load(){
-    __config_core_get "VM_DATASTORE_LIST" "datastore_list"
+datastore::load(){
+    config::core_get "VM_DATASTORE_LIST" "datastore_list"
     VM_DATASTORE_LIST="default${VM_DATASTORE_LIST:+ }${VM_DATASTORE_LIST}"
 }
 
@@ -180,7 +180,7 @@ __datastore_load(){
 # @return non-zero on error
 # @modifies VM_DS_NAME VM_DS_PATH VM_DS_ZFS VM_DS_ZFS_DATASET
 #
-__datastore_get_guest(){
+datastore::get_guest(){
     local _guest="$1"
     local _ds _spec _path _found _zfs _dataset
 
@@ -197,8 +197,8 @@ __datastore_get_guest(){
     if [ -z "${_found}" ]; then
         for _ds in ${VM_DATASTORE_LIST}; do
             [ "${_ds}" = "default" ] && continue
-            __config_core_get "_spec" "path_${_ds}"
-            __datastore_resolve_path "_path" "${_spec}"
+            config::core_get "_spec" "path_${_ds}"
+            datastore::__resolve_path "_path" "${_spec}"
 
             if [ -f "${_path}/${_guest}/${_guest}.conf" ]; then
                 [ "${_spec%%:*}" = "zfs" ] && _zfs="1" && _dataset="${_spec#*:}"
@@ -226,7 +226,7 @@ __datastore_get_guest(){
 # @return non-zero on error
 # @modifies VM_DS_PATH VM_DS_ZFS VM_DS_ZFS_DATASET
 #
-__datastore_get(){
+datastore::get(){
     local _ds="$1"
     local _spec _path _zfs _dataset
 
@@ -239,10 +239,10 @@ __datastore_get(){
         return 0
     fi
 
-    __config_core_get "_spec" "path_${_ds}"
+    config::core_get "_spec" "path_${_ds}"
     [ -z "${_spec}" ] && return 1
 
-    __datastore_resolve_path "_path" "${_spec}" || return 1
+    datastore::__resolve_path "_path" "${_spec}" || return 1
     [ "${_spec%%:*}" = "zfs" ] && _zfs="1" && _dataset="${_spec#*:}"
 
     # set variables
diff --git a/lib/vm-info b/lib/vm-info
--- a/lib/vm-info
+++ b/lib/vm-info
@@ -29,27 +29,27 @@
 #
 # @param optional string _name name of the guest to display
 #
-__vm_info(){
+info::guest(){
     local _name="$1"
     local _bridge_list=$(ifconfig | grep ^bridge | cut -d: -f1)
     local _ds
 
-    __vm_running_load
+    vm::running_load
 
     # see if one guest provided
     if [ -n "${_name}" ]; then
-        __datastore_get_guest "${_name}" || __err "unable to locate virtual machine '${_name}'"
-        __vm_info_guest "${_name}"
+        datastore::get_guest "${_name}" || util::err "unable to locate virtual machine '${_name}'"
+        info::guest_guest "${_name}"
         exit
     fi
 
     # show all guests from all datastores
     for _ds in ${VM_DATASTORE_LIST}; do
-        __datastore_get "${_ds}" || continue
+        datastore::get "${_ds}" || continue
 
         ls -1 "${VM_DS_PATH}" 2>/dev/null | \
         while read _name; do
-            [ -e "${VM_DS_PATH}/${_name}/${_name}.conf" ] && __vm_info_guest "${_name}"
+            [ -e "${VM_DS_PATH}/${_name}/${_name}.conf" ] && info::guest_guest "${_name}"
         done
     done
 }
@@ -59,22 +59,22 @@ __vm_info(){
 #
 # @param optional string _switch name of switch to display
 #
-__vm_info_switch(){
+info::guest_switch(){
     local _switch="$1"
     local _list
 
     # load config file manually using non-core function
     # this means we can share the config_output function with guest
-    __config_load "${vm_dir}/.config/system.conf"
-    __config_get "_list" "switch_list"
+    config::load "${vm_dir}/.config/system.conf"
+    config::get "_list" "switch_list"
 
     if [ -n "${_switch}" ]; then
-        __vm_info_switch_show "${_switch}"
+        info::guest_switch_show "${_switch}"
         exit
     fi
 
     for _switch in ${_list}; do
-        __vm_info_switch_show "${_switch}"
+        info::guest_switch_show "${_switch}"
     done
 }
 
@@ -82,51 +82,51 @@ __vm_info_switch(){
 #
 # @param string _switch the name of the switch
 #
-__vm_info_switch_show(){
+info::guest_switch_show(){
     local _switch="$1"
     local _bridge _vale _id
     local _INDENT="  "
 
     [ -z "${_switch}" ] && return 1
 
-    __config_get "_bridge" "bridge_${_switch}"
-    __config_get "_vale" "vale_${_switch}"
+    config::get "_bridge" "bridge_${_switch}"
+    config::get "_vale" "vale_${_switch}"
 
     echo "------------------------"
     echo "Virtual Switch: ${_switch}"
     echo "------------------------"
 
-    if __checkyesno "${_vale}"; then
+    if util::checkyesno "${_vale}"; then
         echo "${_INDENT}type: vale"
-        __switch_vale_id "_id" "${_switch}"
+        switch::vale_id "_id" "${_switch}"
     elif [ -n "${_bridge}" ]; then
         echo "${_INDENT}type: manual"
         _id="${_bridge}"
     else
         echo "${_INDENT}type: auto"
-        __switch_get_ident "_bridge" "${_switch}"
+        switch::get_ident "_bridge" "${_switch}"
         _id="${_bridge}"
     fi
 
     echo "${_INDENT}ident: ${_id:--}"
 
-    __vm_info_output_config "vlan_${_switch}" "vlan"
-    __vm_info_output_config "nat_${_switch}" "nat"
-    __vm_info_output_config "ports_${_switch}" "physical-ports"
+    info::guest_output_config "vlan_${_switch}" "vlan"
+    info::guest_output_config "nat_${_switch}" "nat"
+    info::guest_output_config "ports_${_switch}" "physical-ports"
 
     if [ -n "${_bridge}" ]; then
         _stats=$(netstat -biI "${_bridge}" |grep '<Link#' | tail -n1 | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }' | awk '{print $5,$2}')
 
         if [ -n "${_stats}" ]; then
-            _b_in=$(__vm_info_bytes_human "${_stats%% *}")
-            _b_out=$(__vm_info_bytes_human "${_stats##* }")
+            _b_in=$(info::guest_bytes_human "${_stats%% *}")
+            _b_out=$(info::guest_bytes_human "${_stats##* }")
 
             echo "${_INDENT}bytes-in: ${_stats%% *} (${_b_in})"
             echo "${_INDENT}bytes-out: ${_stats##* } (${_b_out})"
         fi
 
         # show guest ports
-        __vm_info_switch_ports
+        info::guest_switch_ports
     fi
 
     echo ""
@@ -134,7 +134,7 @@ __vm_info_switch_show(){
 
 # get all guest ports for current bridge
 #
-__vm_info_switch_ports(){
+info::guest_switch_ports(){
     local _port_list=$(ifconfig "${_bridge}" |grep 'member: tap' |awk '{print $2}')
     local _port _guest
 
@@ -152,7 +152,7 @@ __vm_info_switch_ports(){
 #
 # @param string _name name of the guest to display
 #
-__vm_info_guest(){
+info::guest_guest(){
     local _name="$1"
     local _conf="${VM_DS_PATH}/${_name}/${_name}.conf"
     local _INDENT="  "
@@ -162,11 +162,11 @@ __vm_info_guest(){
     [ -z "${_name}" ] && return 1
     [ ! -f "${_conf}" ] && return 1
 
-    __config_load "${_conf}"
+    config::load "${_conf}"
 
     # check local and global runstate
     [ -e "/dev/vmm/${_name}" ] && _RUN="1"
-    __vm_running_check "_global_run" "${_name}"
+    vm::running_check "_global_run" "${_name}"
     _global_run=$(echo "${_global_run}" | tr '[:upper:]' '[:lower:]')
 
     echo "------------------------"
@@ -177,18 +177,18 @@ __vm_info_guest(){
     echo "${_INDENT}datastore: ${VM_DS_NAME}"
 
     # basic guest configuration
-    __vm_info_output_config "loader" "" "default"
-    __vm_info_output_config "uuid" "" "auto"
-    __vm_info_output_config "uefi" "" "no"
-    __vm_info_output_config "cpu"
-    __vm_info_output_config "memory"
+    info::guest_output_config "loader" "" "default"
+    info::guest_output_config "uuid" "" "auto"
+    info::guest_output_config "uefi" "" "no"
+    info::guest_output_config "cpu"
+    info::guest_output_config "memory"
 
     # running system details
     if [ "${_RUN}" = "1" ]; then
         _res_mem=$(bhyvectl --get-stats --vm="${_name}" |grep 'Resident memory' |awk '{print $3}')
 
         if [ -n "${_res_mem}" ]; then
-            _b_res_mem=$(__vm_info_bytes_human "${_res_mem}")
+            _b_res_mem=$(info::guest_bytes_human "${_res_mem}")
             echo "${_INDENT}memory-resident: ${_res_mem} (${_b_res_mem})"
         fi
 
@@ -205,38 +205,38 @@ __vm_info_guest(){
     fi
 
     # network interfaces
-    __vm_info_networking
+    info::guest_networking
 
     # disks
-    __vm_info_disks
+    info::guest_disks
 
     echo ""
 }
 
 # display disks
 #
-__vm_info_disks(){
+info::guest_disks(){
     local _num=0
     local _disk _type _dev _path _size _b_size _used _b_used
     local _INDENT="    "
 
     while [ 1 ]; do
-        __config_get "_disk" "disk${_num}_name"
-        __config_get "_type" "disk${_num}_type"
-        __config_get "_dev" "disk${_num}_dev"
+        config::get "_disk" "disk${_num}_name"
+        config::get "_type" "disk${_num}_type"
+        config::get "_dev" "disk${_num}_dev"
         [ -z "${_disk}" -o -z "${_type}" ] && break
 
         : ${_dev:=file}
 
-        __vm_get_disk_path "_path" "${_name}" "${_disk}" "${_dev}"
+        vm::get_disk_path "_path" "${_name}" "${_disk}" "${_dev}"
 
         echo ""
         echo "  virtual-disk"
         echo "${_INDENT}number: ${_num}"
 
-        __vm_info_output_config "disk${_num}_dev" "device-type" "file"
-        __vm_info_output_config "disk${_num}_type" "emulation"
-        __vm_info_output_config "disk${_num}_opts" "options"
+        info::guest_output_config "disk${_num}_dev" "device-type" "file"
+        info::guest_output_config "disk${_num}_type" "emulation"
+        info::guest_output_config "disk${_num}_opts" "options"
 
         echo "${_INDENT}system-path: ${_path:--}"
 
@@ -257,8 +257,8 @@ __vm_info_disks(){
             esac
 
             if [ -n "${_size}" -a -n "${_used}" ]; then
-                _b_size=$(__vm_info_bytes_human "${_size}")
-                _b_used=$(__vm_info_bytes_human "${_used}")
+                _b_size=$(info::guest_bytes_human "${_size}")
+                _b_used=$(info::guest_bytes_human "${_used}")
                 echo "${_INDENT}bytes-size: ${_size} (${_b_size})"
                 echo "${_INDENT}bytes-used: ${_used} (${_b_used})"
             fi
@@ -270,13 +270,13 @@ __vm_info_disks(){
 
 # display networking configuration
 #
-__vm_info_networking(){
+info::guest_networking(){
     local _num=0
     local _int _id _tag _switch _stats _b_in _b_out
     local _INDENT="    "
 
     while [ 1 ]; do
-        __config_get "_int" "network${_num}_type"
+        config::get "_int" "network${_num}_type"
         [ -z "${_int}" ] && break
 
         echo ""
@@ -284,20 +284,20 @@ __vm_info_networking(){
         echo "${_INDENT}number: ${_num}"
 
         # basic interface config
-        __vm_info_output_config "network${_num}_type" "emulation"
-        __vm_info_output_config "network${_num}_switch" "virtual-switch"
-        __vm_info_output_config "network${_num}_mac" "fixed-mac-address"
-        __vm_info_output_config "network${_num}_device" "fixed-device"
+        info::guest_output_config "network${_num}_type" "emulation"
+        info::guest_output_config "network${_num}_switch" "virtual-switch"
+        info::guest_output_config "network${_num}_mac" "fixed-mac-address"
+        info::guest_output_config "network${_num}_device" "fixed-device"
 
         # if running, try to get some more interface details
         if [ "${_RUN}" = "1" ]; then
-            __config_get "_switch" "network${_num}_switch"
+            config::get "_switch" "network${_num}_switch"
 
             _int=$(ifconfig | grep -B1 "vmnet-${_name}-${_num}-" | head -n1 | cut -d' ' -f1,6)
             _id=${_int%%:*}
             _tag=$(ifconfig | grep "vmnet-${_name}-${_num}-" | cut -d' ' -f2)
 
-            __vm_info_find_bridge "_bridge" "${_id}"
+            info::guest_find_bridge "_bridge" "${_id}"
 
             echo "${_INDENT}active-device: ${_id:--}"
             echo "${_INDENT}desc: ${_tag:--}"
@@ -306,8 +306,8 @@ __vm_info_networking(){
 
             if [ -n "${_id}" ]; then
                 _stats=$(netstat -biI "${_id}" | tail -n1 | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }' | awk '{print $2,$5}')
-                _b_in=$(__vm_info_bytes_human "${_stats%% *}")
-                _b_out=$(__vm_info_bytes_human "${_stats##* }")
+                _b_in=$(info::guest_bytes_human "${_stats%% *}")
+                _b_out=$(info::guest_bytes_human "${_stats##* }")
 
                 echo "${_INDENT}bytes-in: ${_stats%% *} (${_b_in})"
                 echo "${_INDENT}bytes-out: ${_stats##* } (${_b_out})"
@@ -325,27 +325,27 @@ __vm_info_networking(){
 # @param optional string _title title to display instead of using option name
 # @param optional string _default default value to display if not -
 #
-__vm_info_output_config(){
+info::guest_output_config(){
     local _option="$1"
     local _title="$2"
     local _default="$3"
     local _var
 
-    __config_get "_var" "${_option}" "${_default:--}"
+    config::get "_var" "${_option}" "${_default:--}"
     [ -z "${_title}" ] && _title="${_option}"
 
     echo "${_INDENT}${_title}: ${_var}"
 }
 
 # try and find the bridge an interface is a member of.
-# we do this rather than just use __switch_get_ident as
+# we do this rather than just use switch::get_ident as
 # this should be able to locate the bridge even for devices
 # that have been bridged manually and have no switch name configured
 #
 # @param string _var variable to put value into
 # @param string _interface interface to look for
 #
-__vm_info_find_bridge(){
+info::guest_find_bridge(){
     local _var="$1"
     local _interface="$2"
     local _br _found
@@ -369,7 +369,7 @@ __vm_info_find_bridge(){
 #
 # @param int _val the value to convert
 #
-__vm_info_bytes_human(){
+info::guest_bytes_human(){
     local _val="$1" _int _ext
     local _num=1
 
diff --git a/lib/vm-util b/lib/vm-util
--- a/lib/vm-util
+++ b/lib/vm-util
@@ -26,11 +26,11 @@
 
 # make sure we have the right environment
 #
-__setup(){
-    __load_module "vmm"
-    __load_module "nmdm"
-    __load_module "if_bridge"
-    __load_module "if_tap"
+util::setup(){
+    util::load_module "vmm"
+    util::load_module "nmdm"
+    util::load_module "if_bridge"
+    util::load_module "if_tap"
 
     sysctl net.link.tap.up_on_open=1 >/dev/null 2>&1
 }
@@ -39,12 +39,12 @@ __setup(){
 #
 # @param string _mod the module name
 #
-__load_module(){
+util::load_module(){
     local _mod="$1"
     kldstat -qm ${_mod} >/dev/null 2>&1
     if [ $? -ne 0 ]; then
         kldload ${_mod} >/dev/null 2>&1
-        [ $? -ne 0 ] && __err "unable to load ${_mod}.ko!"
+        [ $? -ne 0 ] && util::err "unable to load ${_mod}.ko!"
     fi
 }
 
@@ -54,12 +54,12 @@ __load_module(){
 # 
 # @modifies VM_NO_UG
 #
-__check_bhyve_support(){
+util::check_bhyve_support(){
     local _mesg _result
 
     # basic checks
-    [ `id -u` -ne 0 ] && __err "virtual machines can only be managed by root"
-    [ ${VERSION_BSD} -lt 1000000 ] && __err "please upgrade to FreeBSD 10 or newer for bhyve support"
+    [ `id -u` -ne 0 ] && util::err "virtual machines can only be managed by root"
+    [ ${VERSION_BSD} -lt 1000000 ] && util::err "please upgrade to FreeBSD 10 or newer for bhyve support"
 
     # get features2 line which should include popcnt
     _mesg=$(grep -E '^[ ]+Features2' /var/run/dmesg.boot | tail -n 1)
@@ -69,7 +69,7 @@ __check_bhyve_support(){
 
         # look for pop cnt
         _result=$(echo "${_mesg}" |grep "POPCNT")
-        [ -z "${_result}" ] && __err "it doesn't look like your cpu supports bhyve (missing POPCNT)"
+        [ -z "${_result}" ] && util::err "it doesn't look like your cpu supports bhyve (missing POPCNT)"
     fi
 
     # check ept for intel
@@ -79,7 +79,7 @@ __check_bhyve_support(){
 
         # look for ept
         _result=$(echo "${_mesg}" |grep "EPT")
-        [ -z "${_result}" ] && __err "it doesn't look like your cpu supports bhyve (missing EPT)"
+        [ -z "${_result}" ] && util::err "it doesn't look like your cpu supports bhyve (missing EPT)"
 
         # look for unrestricted guest
         _result=$(echo "${_mesg}" |grep ",UG")
@@ -92,7 +92,7 @@ __check_bhyve_support(){
 #
 # @return success if host has vt-d
 #
-__check_bhyve_iommu(){
+util::check_bhyve_iommu(){
     local _mesg
 
     _mesg=$(acpidump -t |grep DMAR)
@@ -106,7 +106,7 @@ __check_bhyve_iommu(){
 #
 # @param string _serv the name of the service
 #
-__restart_service(){
+util::restart_service(){
     local _serv="$1"
     local _cmd="restart"
 
@@ -115,20 +115,20 @@ __restart_service(){
     [ $? -ne 0 ] && _cmd="start"
 
     service ${_serv} ${_cmd} >/dev/null 2>&1
-    [ $? -ne 0 ] && __warn "failed to ${_cmd} service ${_serv}"
+    [ $? -ne 0 ] && util::warn "failed to ${_cmd} service ${_serv}"
 }
 
 # show version
 #
-__version(){
+util::version(){
     echo "vm-bhyve: Bhyve virtual machine management v${VERSION} (build ${VERSION_INT})"
 }
 
 # show version & usage information
 # we exit after running this
 #
-__usage(){
-    __version
+util::usage(){
+    util::version
     cat << EOT
 Usage: vm ...
     version
@@ -178,7 +178,7 @@ EOT
 #
 # @param string - the message to display
 #
-__err(){
+util::err(){
     echo "${0}: ERROR: $1" >&2
     exit 1
 }
@@ -188,7 +188,7 @@ __err(){
 #
 # @param string - the message to display
 #
-__warn(){
+util::warn(){
     echo "${0}: WARNING: $1" >&2
 }
 
@@ -200,7 +200,7 @@ __warn(){
 #
 # @param string _type whether to rotate guest or main log
 #
-__log_rotate(){
+util::log_rotate(){
     local _type="$1"
     local _lf="vm-bhyve.log"
     local _file _size _guest
@@ -235,7 +235,7 @@ __log_rotate(){
 # @param optional string _guest if _type=guest, the guest name, otherwise do not provide at all
 # @param string _message the message to log
 #
-__log(){
+util::log(){
     local _type="$1"
     local _lf="vm-bhyve.log"
     local _guest _message _file _date
@@ -266,20 +266,20 @@ __log(){
 # @param string _file the file name to write to
 # @param string _message the data to write
 #
-__log_and_write(){
+util::log_and_write(){
     local _type="$1"
     local _guest="$2"
     local _file="${VM_DS_PATH}/${_guest}/$3"
     local _message="$4"
 
     if [ "${_type}" = "write" ]; then
-        __log "guest" "${_guest}" "create file ${_file}"
+        util::log "guest" "${_guest}" "create file ${_file}"
         echo "${_message}" > "${_file}"
     else
         echo "${_message}" >> "${_file}"
     fi
 
-    __log "guest" "${_guest}" " -> ${_message}"
+    util::log "guest" "${_guest}" " -> ${_message}"
 }
 
 # confirm yes or no
@@ -287,7 +287,7 @@ __log_and_write(){
 # @param string _msh message to display
 # @return int success if confirmed
 #
-__confirm(){
+util::confirm(){
     local _msg="$1"
     local _resp
 
@@ -306,7 +306,7 @@ __confirm(){
 # @param _value the value to test
 # @return int 1 if set to "off/false/no/0", 0 otherwise
 #
-__checkyesno(){
+util::checkyesno(){
     local _value="$1"
 
     [ -z "${_value}" ] && return 1
diff --git a/lib/vm-zfs b/lib/vm-zfs
--- a/lib/vm-zfs
+++ b/lib/vm-zfs
@@ -41,7 +41,7 @@
 #
 # @modifies VM_ZFS VM_ZFS_DATASET vm_dir
 #
-__zfs_init(){
+zfs::init(){
     local _zfs
 
     # check for zfs storage location
@@ -50,7 +50,7 @@ __zfs_init(){
 
         # check zfs running
         kldstat -qm zfs >/dev/null 2>&1
-        [ $? -ne 0 ] && __err "ZFS support requested but ZFS not available"
+        [ $? -ne 0 ] && util::err "ZFS support requested but ZFS not available"
 
         # global zfs details
         VM_ZFS="1"
@@ -59,7 +59,7 @@ __zfs_init(){
         # update vm_dir
         # this makes sure it exists, confirms it's mounted & gets correct path in one go
         vm_dir=$(mount | grep "^${VM_ZFS_DATASET} " |cut -d' ' -f3)
-        [ -z "${vm_dir}" ] && __err "unable to locate mountpoint for ZFS dataset ${VM_ZFS_DATASET}"
+        [ -z "${vm_dir}" ] && util::err "unable to locate mountpoint for ZFS dataset ${VM_ZFS_DATASET}"
     fi
 }
 
@@ -68,14 +68,14 @@ __zfs_init(){
 #
 # @param string _name name of the dataset to create
 #
-__zfs_make_dataset(){
+zfs::make_dataset(){
     local _name="$1"
     local _opts="$2"
 
     if [ -n "${_name}" -a "${VM_DS_ZFS}" = "1" ]; then
-        __zfs_format_options "_opts" "${_opts}"
+        zfs::__format_options "_opts" "${_opts}"
         zfs create ${_opts} "${_name}"
-        [ $? -ne 0 ] && __err "failed to create new ZFS dataset ${_name}"
+        [ $? -ne 0 ] && util::err "failed to create new ZFS dataset ${_name}"
     fi
 }
 
@@ -83,12 +83,12 @@ __zfs_make_dataset(){
 #
 # @param string _name name of the dataset to destroy
 #
-__zfs_destroy_dataset(){
+zfs::destroy_dataset(){
     local _name="$1"
 
     if [ -n "${_name}" -a "${VM_DS_ZFS}" = "1" ]; then
         zfs destroy -rf "${_name}" >/dev/null 2>&1
-        [ $? -ne 0 ] && __err "failed to destroy ZFS dataset ${_name}"
+        [ $? -ne 0 ] && util::err "failed to destroy ZFS dataset ${_name}"
     fi
 }
 
@@ -99,13 +99,13 @@ __zfs_destroy_dataset(){
 # @param string _old the name of the dataset to rename
 # @param string _new the new name
 #
-__zfs_rename_dataset(){
+zfs::rename_dataset(){
     local _old="$1"
     local _new="$2"
 
     if [ -n "${_old}" -a -n "${_new}" -a "${VM_DS_ZFS}" = "1" ]; then
         zfs rename "${VM_DS_ZFS_DATASET}/${_old}" "${VM_DS_ZFS_DATASET}/${_new}" >/dev/null 2>&1
-        [ $? -ne 0 ] && __err "failed to rename ZFS dataset ${VM_DS_ZFS_DATASET}/${_old}"
+        [ $? -ne 0 ] && util::err "failed to rename ZFS dataset ${VM_DS_ZFS_DATASET}/${_old}"
     fi
 }
 
@@ -115,19 +115,19 @@ __zfs_rename_dataset(){
 # @param string _size how big to create the dataset
 # @param int _sparse=0 set to 1 for a sparse zvol
 #
-__zfs_make_zvol(){
+zfs::make_zvol(){
     local _name="$1"
     local _size="$2"
     local _sparse="$3"
     local _user_opts="$4"
     local _opt="-V"
 
-    [ ! "${VM_DS_ZFS}" = "1" ] && __err "cannot use ZVOL storage unless ZFS support is enabled"
+    [ ! "${VM_DS_ZFS}" = "1" ] && util::err "cannot use ZVOL storage unless ZFS support is enabled"
     [ "${_sparse}" = "1" ] && _opt="-sV"
 
-    __zfs_format_options "_user_opts" "${_user_opts}"
+    zfs::__format_options "_user_opts" "${_user_opts}"
     zfs create ${_opt} ${_size} -o volmode=dev ${_user_opts} "${_name}"
-    [ $? -ne 0 ] && __err "failed to create new ZVOL ${_name}"
+    [ $? -ne 0 ] && util::err "failed to create new ZVOL ${_name}"
 }
 
 # format options for zfs commands
@@ -136,7 +136,7 @@ __zfs_make_zvol(){
 #
 # @modifies $_val
 #
-__zfs_format_options(){
+zfs::__format_options(){
     local _val="$1"
     local _c_opts="$2"
 
@@ -158,13 +158,13 @@ __zfs_format_options(){
 # @param flag (-f) force snapshot if guest is running
 # @param string _name the name of the guest to snapshot
 #
-__zfs_snapshot(){
+zfs::snapshot(){
     local _name _snap _opt _force _snap_exists
 
     while getopts f _opt; do
         case $_opt in
             f) _force=1 ;;
-            *) __usage ;;
+            *) util::usage ;;
         esac
     done
 
@@ -180,17 +180,17 @@ __zfs_snapshot(){
         _name=${_name%%@*}
     fi
 
-    [ -z "${_name}" ] && __usage
-    __datastore_get_guest "${_name}" || __err "${_name} does not appear to be an existing virtual machine"
-    [ ! "${VM_DS_ZFS}" = "1" ] && __err "cannot snapshot guests on non-zfs datastores"
+    [ -z "${_name}" ] && util::usage
+    datastore::get_guest "${_name}" || util::err "${_name} does not appear to be an existing virtual machine"
+    [ ! "${VM_DS_ZFS}" = "1" ] && util::err "cannot snapshot guests on non-zfs datastores"
     [ -z "${_snap}" ] && _snap=$(date +"%Y-%m-%d-%H:%M:%S")
 
-    if ! __vm_confirm_stopped "${_name}" >/dev/null; then
-        [ -z "${_force}" ] && __err "${_name} must be powered off first (use -f to override)"
+    if ! vm::confirm_stopped "${_name}" >/dev/null; then
+        [ -z "${_force}" ] && util::err "${_name} must be powered off first (use -f to override)"
     fi
 
     zfs snapshot -r ${VM_DS_ZFS_DATASET}/${_name}@${_snap}
-    [ $? -ne 0 ] && __err "failed to create recursive snapshot of virtual machine"
+    [ $? -ne 0 ] && util::err "failed to create recursive snapshot of virtual machine"
 }
 
 # 'vm rollback'
@@ -203,30 +203,30 @@ __zfs_snapshot(){
 # @param flag (-r) force deletion of more recent snapshots
 # @param string _name name of the guest
 #
-__zfs_rollback(){
+zfs::rollback(){
     local _name _snap _opt _force _fs _snap_exists
 
     while getopts r _opt; do
         case $_opt in
             r) _force="-r" ;;
-            *) __usage ;;
+            *) util::usage ;;
         esac
     done
 
     shift $((OPTIND - 1))
 
     _snap_exists=$(echo "${1}" | grep "@")
-    [ -z "${_snap_exists}" ] && __err "a snapshot name must be provided in guest@snapshot format"
+    [ -z "${_snap_exists}" ] && util::err "a snapshot name must be provided in guest@snapshot format"
 
     _name="${1%%@*}"
     _snap="${1##*@}"
 
-    [ -z "${_name}" -o -z "${_snap}" ] && __usage
+    [ -z "${_name}" -o -z "${_snap}" ] && util::usage
 
-    __datastore_get_guest "${_name}" || __err "${_name} does not appear to be an existing virtual machine"
-    [ ! "${VM_DS_ZFS}" = "1" ] && __err "cannot rollback guests on non-zfs datastores"
+    datastore::get_guest "${_name}" || util::err "${_name} does not appear to be an existing virtual machine"
+    [ ! "${VM_DS_ZFS}" = "1" ] && util::err "cannot rollback guests on non-zfs datastores"
 
-    __vm_confirm_stopped "${_name}" || exit 1
+    vm::confirm_stopped "${_name}" || exit 1
 
     # list all datasets and zvols under guest
     zfs list -o name -rHt filesystem,volume ${VM_DS_ZFS_DATASET}/${_name} | \
@@ -243,7 +243,7 @@ __zfs_rollback(){
 # @param string _old the guest to clone
 # @param string _new name of the new guest
 #
-__zfs_clone(){
+zfs::clone(){
     local _old="$1"
     local _name="$2"
     local _fs _newfs _snap _snap_exists _fs_list _entry
@@ -251,8 +251,8 @@ __zfs_clone(){
     local _uuid=$(uuidgen)
 
     # check args and make sure new guest doesn't already exist
-    [ -z "${_old}" -o -z "${_name}" ] && __usage
-    __datastore_get_guest "${_name}" && __err "new guest already exists in ${VM_DS_PATH}/${_name}"
+    [ -z "${_old}" -o -z "${_name}" ] && util::usage
+    datastore::get_guest "${_name}" && util::err "new guest already exists in ${VM_DS_PATH}/${_name}"
 
     # try to get snapshot name
     # we support normal zfs syntax for this
@@ -264,24 +264,24 @@ __zfs_clone(){
     fi
 
     # make sure old guest exists
-    __datastore_get_guest "${_old}" || __err "${_old} does not appear to be an existing virtual machine"
-    [ ! "${VM_DS_ZFS}" = "1" ] && __err "cannot clone guests on non-zfs datastores"
+    datastore::get_guest "${_old}" || util::err "${_old} does not appear to be an existing virtual machine"
+    [ ! "${VM_DS_ZFS}" = "1" ] && util::err "cannot clone guests on non-zfs datastores"
 
     # get list of datasets to copy
     _fs_list=$(zfs list -rHo name -t filesystem,volume "${VM_DS_ZFS_DATASET}/${_old}")
-    [ $? -ne 0 ] && __err "unable to list datasets for ${VM_DS_ZFS_DATASET}/${_old}"
+    [ $? -ne 0 ] && util::err "unable to list datasets for ${VM_DS_ZFS_DATASET}/${_old}"
 
     # generate a short uuid and create snapshot if no custom snap given
     if [ -z "${_snap}" ]; then
-        __vm_confirm_stopped "${_old}" || exit 1
+        vm::confirm_stopped "${_old}" || exit 1
         _snap=$(echo "${_uuid}" |awk -F- '{print $1}')
 
         zfs snapshot -r "${VM_DS_ZFS_DATASET}/${_old}@${_snap}"
-        [ $? -ne 0 ] && __err "failed to create snapshot ${VM_DS_ZFS_DATASET}/${_old}@${_snap}"
+        [ $? -ne 0 ] && util::err "failed to create snapshot ${VM_DS_ZFS_DATASET}/${_old}@${_snap}"
     else
         for _fs in ${_fs_list}; do
             zfs get creation "${_fs}@${_snap}" >/dev/null 2>&1
-            [ $? -ne 0 ] && __err "snapshot ${_fs}@${_snap} doesn't seem to exist"
+            [ $? -ne 0 ] && util::err "snapshot ${_fs}@${_snap} doesn't seem to exist"
         done
     fi
 
@@ -290,7 +290,7 @@ __zfs_clone(){
         _newfs=$(echo "${_fs}" | sed "s@${VM_DS_ZFS_DATASET}/${_old}@${VM_DS_ZFS_DATASET}/${_name}@")
 
         zfs clone "${_fs}@${_snap}" "${_newfs}"
-        [ $? -ne 0 ] && __err "error while cloning dataset ${_fs}@${_snap}"
+        [ $? -ne 0 ] && util::err "error while cloning dataset ${_fs}@${_snap}"
     done
 
     # update new guest files
@@ -304,15 +304,15 @@ __zfs_clone(){
     fi
 
     # update mac addresses and uuid
-    __config_load "${VM_DS_PATH}/${_name}/${_name}.conf"
-    __vm_config_set "${_name}" "uuid" "${_uuid}"
+    config::load "${VM_DS_PATH}/${_name}/${_name}.conf"
+    core::guest_config_set "${_name}" "uuid" "${_uuid}"
 
     # find all network interfaces and change mac
     while [ 1 ]; do
-        __config_get "_entry" "network${_num}_type"
+        config::get "_entry" "network${_num}_type"
         [ -z "${_entry}" ] && break
 
-        __vm_generate_static_mac
+        vm::generate_static_mac
         _num=$((_num + 1))
     done
 }
@@ -325,7 +325,7 @@ __zfs_clone(){
 # @param optional string (-d) description of the image
 # @param string _name name of guest to take image of
 #
-__zfs_image_create(){
+zfs::image_create(){
     local _name _opt _desc
     local _uuid _snap _date _no_compress _filename
 
@@ -333,7 +333,7 @@ __zfs_image_create(){
         case $_opt in
             d) _desc=${OPTARG} ;;
             u) _no_compress="1" ;;
-            *) __usage ;;
+            *) util::usage ;;
         esac
     done
 
@@ -345,18 +345,18 @@ __zfs_image_create(){
 
     [ -z "${_desc}" ] && _desc="No description provided"
 
-    __datastore_get_guest "${_name}" || __err "${_name} does not appear to be a valid virtual machine"
-    [ -z "${VM_ZFS}" -o -z "${VM_DS_ZFS}" ] && __err "this command is only supported on zfs datastores"
+    datastore::get_guest "${_name}" || util::err "${_name} does not appear to be a valid virtual machine"
+    [ -z "${VM_ZFS}" -o -z "${VM_DS_ZFS}" ] && util::err "this command is only supported on zfs datastores"
 
     # create the image dataset if we don't have it
     if [ ! -e "${vm_dir}/images" ]; then
         zfs create "${VM_ZFS_DATASET}/images" >/dev/null 2>&1
-        [ $? -ne 0 ] && __err "failed to create image store ${VM_ZFS_DATASET}/images"
+        [ $? -ne 0 ] && util::err "failed to create image store ${VM_ZFS_DATASET}/images"
     fi
 
     # try to snapshot
     zfs snapshot -r "${VM_DS_ZFS_DATASET}/${_name}@${_snap}" >/dev/null 2>&1
-    [ $? -ne 0 ] && __err "failed to create snapshot of source dataset ${VM_DS_ZFS_DATASET}/${_name}@${_snap}"
+    [ $? -ne 0 ] && util::err "failed to create snapshot of source dataset ${VM_DS_ZFS_DATASET}/${_name}@${_snap}"
 
     # copy source
     if [ -n "${_no_compress}" ]; then
@@ -391,14 +391,14 @@ __zfs_image_create(){
 # @param string _uuid the uuid of the image to use
 # @param string _name name of the new guest
 #
-__zfs_image_provision(){
+zfs::image_provision(){
     local _uuid _name _file _oldname _entry _num=0 _type
     local _datastore="default"
 
     while getopts d: _opt ; do
         case $_opt in
             d) _datastore="${OPTARG}" ;;
-            *) __usage ;;
+            *) util::usage ;;
         esac
     done
 
@@ -406,20 +406,20 @@ __zfs_image_provision(){
     _uuid="$1"
     _name="$2"
 
-    [ -z "${_uuid}" -o -z "${_name}" ] && __usage
-    [ ! -e "${vm_dir}/images/${_uuid}.manifest" ] && __err "unable to locate image with uuid ${_uuid}"
-    __datastore_get_guest "${_name}" && __err "new guest already exists in ${VM_DS_PATH}/${_name}"
+    [ -z "${_uuid}" -o -z "${_name}" ] && util::usage
+    [ ! -e "${vm_dir}/images/${_uuid}.manifest" ] && util::err "unable to locate image with uuid ${_uuid}"
+    datastore::get_guest "${_name}" && util::err "new guest already exists in ${VM_DS_PATH}/${_name}"
 
     # get the data filename
     _file=$(sysrc -inqf "${vm_dir}/images/${_uuid}.manifest" filename)
     _type=${_file##*.}
 
     _oldname=$(sysrc -inqf "${vm_dir}/images/${_uuid}.manifest" name)
-    [ -z "${_file}" -o -z "${_oldname}" ] && __err "unable to locate required details from the specified image manifest"
-    [ ! -e "${vm_dir}/images/${_file}" ] && __err "image data file does not exist: ${vm_dir}/images/${_file}"
+    [ -z "${_file}" -o -z "${_oldname}" ] && util::err "unable to locate required details from the specified image manifest"
+    [ ! -e "${vm_dir}/images/${_file}" ] && util::err "image data file does not exist: ${vm_dir}/images/${_file}"
 
     # get the datastore to create on
-    __datastore_get "${_datastore}" || __err "unable to locate datastore '${_datastore}'"
+    datastore::get "${_datastore}" || util::err "unable to locate datastore '${_datastore}'"
 
     # try to recieve
     echo "Unpacking guest image, this may take some time..."
@@ -428,31 +428,31 @@ __zfs_image_provision(){
     case ${_type} in
         zfs) cat "${vm_dir}/images/${_file}" | zfs recv "${VM_DS_ZFS_DATASET}/${_name}" ;;
         xz)  cat "${vm_dir}/images/${_file}" | xz -d | zfs recv "${VM_DS_ZFS_DATASET}/${_name}" ;;
-        *)   __err "unsupported guest image type - '${_type}'" ;;
+        *)   util::err "unsupported guest image type - '${_type}'" ;;
     esac
 
     # error unpacking?
-    [ $? -ne 0 ] && __err "errors occured while trying to unpackage the image file"
+    [ $? -ne 0 ] && util::err "errors occured while trying to unpackage the image file"
 
     # remove the original snapshot
     zfs destroy -r "${VM_DS_ZFS_DATASET}/${_name}@${_uuid%%-*}" >/dev/null 2>&1
 
     # rename the guest configuration file
     mv "${VM_DS_PATH}/${_name}/${_oldname}.conf" "${VM_DS_PATH}/${_name}/${_name}.conf" >/dev/null 2>&1
-    [ $? -ne 0 ] && __err "unpackaged image but unable to update guest configuration file"
+    [ $? -ne 0 ] && util::err "unpackaged image but unable to update guest configuration file"
 
     # update mac addresses and create a new uuid
     _uuid=$(uuidgen)
 
-    __config_load "${VM_DS_PATH}/${_name}/${_name}.conf"
-    __vm_config_set "${_name}" "uuid" "${_uuid}"
+    config::load "${VM_DS_PATH}/${_name}/${_name}.conf"
+    core::guest_config_set "${_name}" "uuid" "${_uuid}"
 
     # find all network interfaces and change mac
     while [ 1 ]; do
-        __config_get "_entry" "network${_num}_type"
+        config::get "_entry" "network${_num}_type"
         [ -z "${_entry}" ] && break
 
-        __vm_generate_static_mac
+        vm::generate_static_mac
         _num=$((_num + 1))
     done
 
@@ -464,7 +464,7 @@ __zfs_image_provision(){
 # 'vm image list'
 # list available images
 #
-__zfs_image_list(){
+zfs::image_list(){
     local _file _uuid _ext
     local _format="%-38s %-16s %-30s %s\n"
 
@@ -490,16 +490,16 @@ __zfs_image_list(){
 #
 # @param string _uuid the uuid of the image
 #
-__zfs_image_destroy(){
+zfs::image_destroy(){
     local _uuid="$1"
     local _file
 
-    [ -z "${_uuid}" ] && __usage
-    [ ! -e "${vm_dir}/images/${_uuid}.manifest" ] && __err "unable to locate image with uuid ${_uuid}"
+    [ -z "${_uuid}" ] && util::usage
+    [ ! -e "${vm_dir}/images/${_uuid}.manifest" ] && util::err "unable to locate image with uuid ${_uuid}"
 
     # get the image filename
     _file=$(sysrc -inqf "${vm_dir}/images/${_uuid}.manifest" filename)
-    [ -z "${_file}" ] && __err "unable to locate filename for the specified image"
+    [ -z "${_file}" ] && util::err "unable to locate filename for the specified image"
 
     unlink "${vm_dir}/images/${_uuid}.manifest"
     unlink "${vm_dir}/images/${_file}"
