Add support for switch address/mtu/private New options to 'vm switch create' to allow an ip and/or mtu to be assigned to standard/vxlan switches. Also standard,vxlan & custom switches can be set as private so no guest interfaces can communicate.

diff --git a/lib/vm-switch b/lib/vm-switch
--- a/lib/vm-switch
+++ b/lib/vm-switch
@@ -54,25 +54,27 @@ switch::init(){
 #
 switch::list(){
     local _switchlist _switch _type
-    local _id _format="%-15s %-10s %-11s %-9s %-12s %s\n"
+    local _id _format="%s^%s^%s^%s^%s^%s^%s^%s^%s\n"
 
     config::core::get "_switchlist" "switch_list"
 
-    printf "${_format}" "NAME" "TYPE" "IDENT" "VLAN" "NAT" "PORTS"
+    {
+        printf "${_format}" "NAME" "TYPE" "IDENT" "ADDRESS" "PRIVATE" "MTU" "VLAN" "NAT" "PORTS"
 
-    if [ -n "${_switchlist}" ]; then
-        for _switch in ${_switchlist}; do
-            # get the switch type
-            config::core::get "_type" "type_${_switch}"
+        if [ -n "${_switchlist}" ]; then
+            for _switch in ${_switchlist}; do
+                # get the switch type
+                config::core::get "_type" "type_${_switch}"
 
-            case "${_type}" in
-                vale)   switch::vale::show "${_switch}" "${_format}" ;;
-                vxlan)  switch::vxlan::show "${_switch}" "${_format}" ;;
-                manual) switch::manual::show "${_switch}" "${_format}" ;;
-                *)      switch::standard::show "${_switch}" "${_format}" ;;
-            esac
-        done
-    fi
+                case "${_type}" in
+                    vale)   switch::vale::show "${_switch}" "${_format}" ;;
+                    vxlan)  switch::vxlan::show "${_switch}" "${_format}" ;;
+                    manual) switch::manual::show "${_switch}" "${_format}" ;;
+                    *)      switch::standard::show "${_switch}" "${_format}" ;;
+                esac
+            done
+        fi
+    } | column -ts^
 }
 
 # create a new virtual switch
@@ -82,15 +84,18 @@ switch::list(){
 switch::create(){
     local _switch
     local _type="standard"
-    local _list _curr _vlan _if _bridge
+    local _list _curr _vlan _if _bridge _addr _mtu _priv
 
     # process options
-    while getopts t:i:n:b: _opt; do
+    while getopts t:i:n:b:a:m:p _opt; do
         case ${_opt} in
             t) _type="${OPTARG}" ;;
             i) _if="${OPTARG}" ;;
             n) _vlan="${OPTARG}" ;;
             b) _bridge="${OPTARG}" ;;
+            a) _addr="${OPTARG}" ;;
+            m) _mtu="${OPTARG}" ;;
+            p) _priv="yes" ;;
             *) util::usage ;;
         esac
     done
@@ -110,17 +115,30 @@ switch::create(){
 
     # check vlan number
     if [ -n "${_vlan}" ]; then
-       echo "${_vlan}" | egrep -qs '^[0-9]{1,4}$'
-       [ $? -ne 0 ] && util::err "invalid vlan number"
-       [ ${_vlan} -ge 4095 ] && util::err "invalid vlan number"
+        echo "${_vlan}" | egrep -qs '^[0-9]{1,4}$'
+        [ $? -ne 0 ] && util::err "invalid vlan number"
+        [ ${_vlan} -ge 4095 ] && util::err "invalid vlan number"
+    fi
+
+    # check address
+    if [ -n "${_addr}" ]; then
+        echo "${_addr}" | egrep -qs '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]{1,2}$'
+        [ $? -ne 0 ] && util::err "address must be supplied in CIDR notation (a.b.c.d/prefix-len)"
+    fi
+
+    # check mtu
+    if [ -n "${_mtu}" ]; then
+        echo "${_mtu}" | egrep -qs '^[0-9]{3,4}$'
+        [ $? -ne 0 ] && util::err "invalid mtu"
+        [ ${_mtu} -gt 9000 ] && util::err "invalid mtu"
     fi
 
     # check switch type
     case "${_type}" in
-        standard) switch::standard::create "${_switch}" "${_if}" "${_vlan}" ;;
-        manual)   switch::manual::create "${_switch}" "${_bridge}" ;;
-        vale)     switch::vale::create "${_switch}" ;;
-        vxlan)    switch::vxlan::create "${_switch}" "${_if}" "${_vlan}" ;;
+        standard) switch::standard::create ;;
+        manual)   switch::manual::create ;;
+        vale)     switch::vale::create ;;
+        vxlan)    switch::vxlan::create ;;
         *)        util::err "invalid switch type - '${_type}'" ;;
     esac
 }
@@ -151,6 +169,7 @@ switch::remove(){
     if [ $? -eq 0 ]; then
         config::core::remove "switch_list" "${_switch}"
         config::core::remove "ports_${_switch} vlan_${_switch} nat_${_switch} type_${_switch}"
+        config::core::remove "addr_${_switch} private_${_switch} mtu_${_switch}"
     else
         util::err "failed to remove virtual switch"
     fi
@@ -251,7 +270,21 @@ switch::type(){
     local _var="$1"
     local _switch="$2"
 
+    [ -z "${_switch}" ] && return 1
     config::core::get "${_var}" "type_${_switch}"
+}
+
+# check if a switch is configured for private members
+#
+# @param string _switch switch name
+# @return succes (0) if it's private
+#
+switch::private(){
+    local _switch="$1"
+    local _priv
+
+    config::core::get "_priv" "private_${_switch}"
+    util::checkyesno "${_priv}"
 }
 
 # get the bridge id for a virtual switch
@@ -263,6 +296,8 @@ switch::id(){
     local _var="$1"
     local _switch="$2"
     local _type
+
+    [ -z "${_switch}" ] && return 1
 
     # get switch type
     config::core::get "_type" "type_${_switch}"
diff --git a/lib/vm-switch-vxlan b/lib/vm-switch-vxlan
--- a/lib/vm-switch-vxlan
+++ b/lib/vm-switch-vxlan
@@ -31,7 +31,7 @@
 #
 switch::vxlan::init(){
     local _name="$1"
-    local _id _vlan _if _addr
+    local _id _vlan _if _maddr _addr
 
     # see if the bridge already exists
     switch::standard::id "_id" "${_name}" && return 0
@@ -41,26 +41,30 @@ switch::vxlan::init(){
     config::core::get "_if" "ports_${_name}"
     [ -z "${_vlan}" -o -z "${_if}" ] && return 1
 
-    # create a bridge for this switch
-    _id=$(ifconfig bridge create description "vm-${_name}" up 2>/dev/null)
-    [ $? -ne 0 ] && util::err "failed to create bridge interface for switch ${_name}"
-
     # get local address for this interface
     _local=$(ifconfig ${_if} | grep "inet " | cut -d" " -f 2)
     [ -z "${_local}" ] && return 1
 
     # come up with an ip address for multicast data
-    switch::vxlan::__multicast "_addr" "${_name}"
+    switch::vxlan::__multicast "_maddr" "${_name}"
 
     # create the vxlan interface
-    ifconfig "vxlan${_vlan}" create vxlanid "${_vlan}" vxlanlocal "${_local}" vxlangroup "${_addr}" \
+    ifconfig "vxlan${_vlan}" create vxlanid "${_vlan}" vxlanlocal "${_local}" vxlangroup "${_maddr}" \
       vxlandev "${_if}" description "vm-vxlan-${_switch}" up >/dev/null 2>&1
     [ $? -ne 0 ] && return 1
+
+    # create a bridge for this switch
+    _id=$(ifconfig bridge create description "vm-${_name}" up 2>/dev/null)
+    [ $? -ne 0 ] && util::err "failed to create bridge interface for switch ${_name}"
 
     # bridge vxlan to our guest switch
     # static route traffic for this multicast address via our specified interface
     ifconfig "${_id}" addm "vxlan${_vlan}"
-    route add -net ${_addr}/32 -iface ${_if} >/dev/null 2>&1
+    route add -net ${_maddr}/32 -iface ${_if} >/dev/null 2>&1
+
+    # custom address for bridge?
+    config::core::get "_addr" "addr_${_name}"
+    [ -n "${_addr}" ] && ifconfig "${_id}" inet ${_addr}
 }
 
 # show the configuration details for a vxlan switch
@@ -71,25 +75,20 @@ switch::vxlan::init(){
 switch::vxlan::show(){
     local _name="$1"
     local _format="$2"
-    local _id _vlan _port
+    local _id _vlan _port _addr _priv
 
     switch::standard::id "_id" "${_name}"
     config::core::get "_vlan" "vlan_${_name}"
     config::core::get "_port" "ports_${_name}"
+    config::core::get "_addr" "addr_${_name}"
+    config::core::get "_priv" "private_${_name}" "no"
 
-    printf "${_format}" "${_name}" "vxlan" "${_id}" "${_vlan}" "n/a" "${_port}"
+    printf "${_format}" "${_name}" "vxlan" "${_id}" "${_addr}" "${_priv}" "n/a" "${_vlan}" "n/a" "${_port}"
 }
 
 # create a vxlan switch
 #
-# @param string _switch the switch name
-# @param string _if interface to use for vxlan traffic
-# @param string _vlan vxlan id number
-#
 switch::vxlan::create(){
-    local _switch="$1"
-    local _if="$2"
-    local _vlan="$3"
 
     # we must have an interface and vlan to use
     [ -z "${_if}" -o -z "${_vlan}" ] && util::err "vxlan switches must be created with an interface and vlan id specified"
@@ -99,6 +98,9 @@ switch::vxlan::create(){
     config::core::set "type_${_switch}" "vxlan"
     config::core::set "vlan_${_switch}" "${_vlan}"
     config::core::set "ports_${_switch}" "${_if}"
+
+    [ -n "${_addr}" ] && config::core::set "addr_${_switch}" "${_addr}"
+    [ -n "${_priv}" ] && config::core::set "private_${_switch}" "${_priv}"
 
     config::core::load
     switch::vxlan::init "${_switch}"
@@ -110,7 +112,7 @@ switch::vxlan::create(){
 #
 switch::vxlan::remove(){
     local _switch="$1"
-    local _id _vlan _addr
+    local _id _vlan _maddr
     
     # try to get guest bridge and vxlan id
     switch::standard::id "_id" "${_switch}"
@@ -119,8 +121,8 @@ switch::vxlan::remove(){
 
     # get the multicast address we used for this switch
     # and try to remove any route we may have added
-    switch::vxlan::__multicast "_addr" "${_switch}"
-    route del -net "${_addr}/32" >/dev/null 2>&1
+    switch::vxlan::__multicast "_maddr" "${_switch}"
+    route del -net "${_maddr}/32" >/dev/null 2>&1
 
     # destroy the guest bridge
     ifconfig ${_id} destroy >/dev/null 2>&1
