Fix exit status for many vm commands
The pattern "[ $? -ne 0 ] && util::err ..." is problematic since it
leaves an exit status of 1 if the test fails, which is the non-error
case. So various commands (e.g., vm datastore add) return status 1 even
when they succeed if this pattern appears as the last line of a command
implementation.

Fix this by mechanically converting this pattern to
"[ $? -eq 0 ] || util:err ...".

diff --git a/lib/vm-switch-standard b/lib/vm-switch-standard
--- a/lib/vm-switch-standard
+++ b/lib/vm-switch-standard
@@ -37,7 +37,7 @@ switch::standard::init(){
 
     # create a bridge for this switch
     _id=$(ifconfig bridge create description "vm-${_name}" priority 0 up 2>/dev/null)
-    [ $? -ne 0 ] && util::err "failed to create bridge interface for switch ${_name}"
+    [ $? -eq 0 ] || util::err "failed to create bridge interface for switch ${_name}"
 
     # try to set ip address
     config::core::get "_addr" "addr_${_name}"
@@ -247,7 +247,7 @@ switch::standard::__configure_port(){
         # create if needed
         if [ -z "${_vid}" ]; then
             _vid=$(ifconfig vlan create vlandev "${_port}" vlan "${_vlan}" description "vm-vlan-${_port}-${_vlan}" up)
-            [ $? -ne 0 ] && util::err "failed to create vlan interface for port ${_port} on switch ${_switch}"
+            [ $? -eq 0 ] || util::err "failed to create vlan interface for port ${_port} on switch ${_switch}"
         fi
 
         ifconfig ${_id} addm ${_vid} >/dev/null 2>&1
@@ -256,7 +256,7 @@ switch::standard::__configure_port(){
         ifconfig ${_id} addm ${_port} >/dev/null 2>&1
     fi
 
-    [ $? -ne 0 ] && util::err "failed to add member ${_port} to the virtual switch ${_switch}"
+    [ $? -eq 0 ] || util::err "failed to add member ${_port} to the virtual switch ${_switch}"
 }
 
 # unconfigure a local port
diff --git a/lib/vm-util b/lib/vm-util
--- a/lib/vm-util
+++ b/lib/vm-util
@@ -44,7 +44,7 @@ util::load_module(){
     kldstat -qm ${_mod} >/dev/null 2>&1
     if [ $? -ne 0 ]; then
         kldload ${_mod} >/dev/null 2>&1
-        [ $? -ne 0 ] && util::err "unable to load ${_mod}.ko!"
+        [ $? -eq 0 ] || util::err "unable to load ${_mod}.ko!"
     fi
 }
 
